name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: unittest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "7.3.14"
      - uses: actions/checkout@v2
      - name: Verify unittest DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'unittest'"
      - name: Create 2nd Database
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE DATABASE IF NOT EXISTS unittest_second;"
      - name: Verify unittest_second DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'unittest_second'"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Migration Database
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ""
          DB_DATABASE: unittest
        run: php artisan migrate
      - name: Dump data
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ""
          DB_DATABASE: unittest
        run: php artisan db:seed
      - name: Create oauth key
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ""
          DB_DATABASE: unittest
        run: php artisan passport:install --force
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ""
          DB_DATABASE: unittest
        run: vendor/bin/phpunit
